name: "Terraform Workflow"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from your repository
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # Set up Terraform (this will install Terraform)
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.3.0'  # You can specify your desired Terraform version

      # Cache Terraform providers (optional, to speed up subsequent runs)
      - name: Cache Terraform providers
        uses: actions/cache@v2
        with:
          path: ~/.terraform.d/plugins
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Validate the Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # Run Terraform Plan (this will output the execution plan)
      - name: Terraform Plan
        run: terraform plan  # Specify the tfvars file

      # Apply the Terraform plan
      - name: Terraform Apply
        run: terraform apply -auto-approve  # Automatically apply using tfvars file