name: "Terraform Workflow"

on:
  workflow_dispatch:  # Allows you to manually trigger the workflow

permissions:
  contents: read  # Required to checkout the code

jobs:
  terraform:
    runs-on: ubuntu-latest  # Using the latest Ubuntu runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.3.0'  # Specify the desired Terraform version

      # Step 3: Set AWS Credentials using GitHub Secrets
      - name: Set AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Validate the Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # Step 6: Run Terraform Plan
      - name: Terraform Plan
        run: terraform plan  # Use the tfvars file

      # Step 7: Apply the Terraform plan
      - name: Terraform Apply
        run: terraform apply -auto-approve  # Automatically approve the apply
