name: "Terraform Workflow"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from your repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Validate the Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # Run Terraform Plan (this will output the execution plan)
      - name: Terraform Plan
        run: terraform plan   # Specify the tfvars file

      # Apply the Terraform plan
      - name: Terraform Apply
        run: terraform apply   # Automatically apply using tfvars file