name: "Git Hub Actions"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sample-job:  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Run a script
        run: echo "Merge the changes"